### PR TITLE
kwm: listen for display resolution change & update

### PR DESCRIPTION
**Pull request by cHoco**
Really open for comments both on functionality and stye (tried to mimic yours as much as possible)

### CODE REVIEW

**Comment by koekeishiya** [comment]
Nothing wrong code-wise, however, the `ApplyNodeContainer()` part of your `UpdateActiveSpace()` function will only work on the focused space of the display. Windows located on the other spaces have to be flagged with a `UpdateSpaceOnTransitionEnd` kind of thing.

**Comment by cHoco** [comment]
Ops, I was only using one space when testing this so I didn't notice XD Is it possible to resize window in another space (not the focused one)?

**Comment by koekeishiya** [comment]
> Is it possible to resize window in another space (not the focused one)?

Not that I know off. The accessibility API only let you interact with windows on the active space.

**Comment by cHoco** [comment]
> I can merge this PR and do the required change to have it affect all spaces, if you'd like.

Whatever you prefer works for me :) If you can wait I can add the missing changes.
If I understand correctly we should update the `UpdateSpaceOfScreen()` to apply the container only if the space is the current active and instead flag the space as *to be updated* if not (maybe by adding a `bool` in `space_info` structure?)
And then modify the `UpdateActiveSpace()` function to check if the new space was flagged and update the container in that case?

**Comment by koekeishiya** [comment]
Yeah that's pretty much it.

**Comment by cHoco** [comment]
Rebased and added logic for later update, as always open for comments

**Comment by koekeishiya** [comment]
```
else if (Space->NeedsUpdate)
{
    UpdateSpaceOfScreen(Space, KWMScreen.Current);
}
```

This part would be better on line 289, inside the `PrevSpace != ActiveSpace` branch just above the `if(Space->FocusedWindowID)` thing. e.g:
```
if(Space->NeedsUpdate)
   UpdateSpaceOfScreen(Space, KWMScreen.Current);

if(Space->FocusedWindowID != 0) ...
```

**Comment by cHoco** [comment]
:+1:

**Comment by koekeishiya** [comment]
Seems to work great, thanks!

**Pull request merged**
