### PR TITLE
kwm-overlay: Inset stroke and frame for better rendering

### PR DESCRIPTION
**Pull request by cHoco**
I've tried kwm again today, and the project matured a lot, great work!

I noticed the overlay rendering wasn't perfect and it was really bugging me out so I fixed it.
First I inset the frame of the overlay by the negative value of the stroke width, so we have a rect big enough for the stroke. Then I inset the bezier path of half of the stroke width since the *drawing* is performed half outside and half inside the path.
I haven't started learning Swift so if you see some bad practices or wrong code style, please correct me.

### CODE REVIEW

**Comment by koekeishiya** [comment]
I honestly do not know how Swift either. The kwm-overlay app was created by @chrishoage, so he is honestly the guy to talk to regarding this.

I'm not completely sure why the drawing is as is, but there may be a reason for it.

Offtopic:
In regards to Kwm, I had worked on it "seriously" for about 3weeks, by the time it got seemingly popular on github, and so it has only  been in development for about 3months give or take.

There is a lot I'm hoping to do still, but lack of time is rather frustrating.

**Comment by chrishoage** [comment]
This was the first time I wrote any swift (or any OS X code). I applied this patch locally and it is indeed better! 

Thanks for fixing this! 

@koekeishiya this looks good to me, feel free to merge it if you like it. 

The only "issue" I found is all borders are bigger with this new logic. Not a problem because it can be easily reconfigured in the `kwmrc` file, but overall this PR is an improvement over what I had previously. Good show!

**Comment by koekeishiya** [comment]
> this looks good to me, feel free to merge it if you like it. 
Aight thats really all the confirmation I need.

Thanks!

**Comment by cHoco** [comment]
@koekeishiya I've tried so many tools to enhance window management on OS X, even wrote a tiling wm in slate once (https://github.com/jigish/slate) but I was never satisfied by them... Instead you project, even from the start, felt better. Today after I reinstalled it I was happily surprised by the many enhancements you made! I'll keep using it this week and report back any issue I find and hopefully help fixing them :D

@chrishoage  Yes! I forgot to mention it, since we're now drawing the full stroke people should probably divide by half the value they're using right now as border width to have similar appearance. Awesome work on the overlay program!

**Pull request merged**
