### PR TITLE
Update border offset logic to use line width

### PR DESCRIPTION
**Pull request by chrishoage**
This updates the border offset depending on the width of the stroke to account for wide border widths.

### CODE REVIEW

**Comment by koekeishiya** [comment]
I'm gonna revert this change, as it causes the border to not correctly snap/round the corners in a lot of OSX Applications windows.

**Comment by chrishoage** [comment]
Huh, I didn't run into that at all when I was testing. Do you have a screenshot / problem application. 

Perhaps this should just be a config value instead of a function of the border width?

**Comment by koekeishiya** [comment]
I did not take a screenshot of it, however it can be reproduced by setting border size to 4.
It happened with programs such as skype, finder, preview and similar.

**Comment by chrishoage** [comment]
Ah, my border was too think. Can repo, I'll fix it.

**Comment by chrishoage** [comment]
I missed that the radius was changed to use the border width. One possible solution is to make the border radius twice the size of the border width. Looks like the attached screenshot. Is this acceptable? 

screen shot 2016-02-01 at 10 08 24 am

**Comment by koekeishiya** [comment]
Doesn't look to bad, how does it look if you use 1.5*border width?

**Comment by chrishoage** [comment]
A very small gap shows. 

screen shot 2016-02-01 at 10 18 04 am

**Comment by chrishoage** [comment]
I missed you 1.75 edit. It looks better, but still an ever so slight space around the rounded corner of the window. 

screen shot 2016-02-01 at 10 23 26 am

**Comment by koekeishiya** [comment]
I'm ok with how that looks.
Does it still look good for other bordersizes as well, e.g 3, 5,8,10

**Comment by chrishoage** [comment]
I do think so. I'll make another PR and you can try it out before merging.

**Pull request merged**
