### PR TITLE
Use AX API in kwm-overlay + makefile refactor

### PR DESCRIPTION
**Pull request by cHoco**
I encountered a little problem while implementing it for all windows, because we have to use a private API, and doing so from swift is a nightmare!
I was able to produce something that seems to work, but I would gladly prefer others opinion and some testing by whoever can.
I also refactored the makefile in the process because during testing it was bugging me quite a bit that we had to rebuild everything every time :dancer:

### CODE REVIEW

**Comment by chrishoage** [comment]
> doing so from swift is a nightmare!

You're under no obligation to use Swift, the only reason I did was because Obj-C syntax scares me and I wanted an excuse to try / learn Swift. 

Feel free to can the entire kwm-overlay.swift file if Obj-C works better for this.

**Comment by koekeishiya** [comment]
I was gonna look through the code and see if I could simplify it a bit, however I've completely forgotten why the code is doing what it does in the first place..

**Comment by koekeishiya** [comment]
Right so it works just fine, however, if you want the makefile change there, could you move all the .o files in a obj dir in the root folder, as I find it annoying to have them laying in the source folder.

**Comment by cHoco** [comment]
@chrishoage Yeah, we'll probably have to move away from swift in the near future, since interacting with C api is troublesome, but it was a great learning experience nevertheless for both me and you :smile: 

@koekeishiya I updated the makefile to create an obj dir and the corresponding subdirs. I also added a check to update the marked border on resize of a fucused window if the two match.
I wanted to propose the makefile changes in a dedicated PR but the new swift magic required some makefile refactoring and I decide to include both. I'm sorry if that's a problem, I could try making the changes mutually exclusive if that's an issue.

**Comment by koekeishiya** [comment]
Seems fine now, thanks!

**Comment by dominiklohmann** [comment]
I can still get the border to not properly update in the Safari search bar. When clicking with the mouse on a suggestion, the window border for the suggestions window (which shouldn't be a thing anyways, but that's probably unrelated) doesn't get removed until you move the mouse or get kwm to update the focus.

**Comment by cHoco** [comment]
The Safari issue is because we are not listening to every notification, and for some reason Safari doesn't get automatically the focus after that window is closed. Would you mind trying out this diff? https://gist.github.com/cHoco/c804e498f2ffc4084c82

This is just a temporary hack, KWMFocus isn't updated when that window is closed that's the main issue. Or maybe we shouldn't even focus that type of window.

**Comment by dominiklohmann** [comment]
That fixes it, now it's only getting a border when you move the mouse over it. 

Thanks! Another issue with that is that the border is smaller than the actual suggestions window, which did not happen before your pull request. Not sure what's going on there. The border dies also not get resized when you continue typing and the list of suggestions shrinks or grows.

**Comment by koekeishiya** [comment]
Safari itself acts very weird because every ui-element is of type AXStandardWindow, and on Layer 0, which is the exact identifier used by normal application windows.

There are probably still some workarounds to this issue, but it is not really part of my priorities at this time.

**Comment by koekeishiya** [comment]
I sometimes get this error with the latest Kwm overlay, causing all of Kwm to crash.

`fatal error: unexpectedly found nil while unwrapping an Optional value`

**Comment by koekeishiya** [comment]
I went ahead and actually undid changes performed here. The reason is all of the random swift-related bugs that I personally can not fix and thus unable to maintain the kwm-overlay application on my own.

kwm-overlay is now just a "dummy" program that parses input it receives. I removed all the APIs that would call into OSX to retrieve window information.

Kwm is now responsible for doing all of the above logic and this allows me to perform proper error handling as I can actual program in C. This change preserves the fixes that this pull request introduces, so there should be no difference in behaviour.

**Comment by cHoco** [comment]
It's just a better solution, I completly agree :+1:

**Pull request merged**
