### PR TITLE
Add support for radius config

### PR DESCRIPTION
**Pull request by chrishoage**
This adds support for setting the radius though `kwmc config *-border radius`.

It defaults to the old behavior (stroke width + 4) if `rad` isn't set. If `rad` is set, it uses that value (a value of 0 will turn off the border radius)

### CODE REVIEW

**Comment by koekeishiya** [comment]
It appears that I have to use a radius value of 8 to get the same looks I had before this change.
This is not a problem or anything, just thought I'd mention it in case it should be the default value maybe instead of 4.

**Comment by chrishoage** [comment]
If you were using a width of 4 a value of 8 makes sense.

Right now the default is the previous logic: width + 4

**Comment by koekeishiya** [comment]
edited last post a bit to late: I don't think the case of width+4 ever happens, because Kwm will always pass in a value for rad = 0, if the user hasnt specified one.

**Comment by chrishoage** [comment]
Ah, I wasn't aware you were sending a value of 0 if it isn't set. Let me know if you run into issues when you don't send the value.

**Comment by koekeishiya** [comment]
Would it be possible to have the users just specify -1 or something like that to have it be disabled? That way 0 can make it use default behaviour (width +4), this way it's a lot easier to manage with Kwm, cause since 0 is the value of uninitialized, I don't have to create a bool or something to track if the users wanted 0 or if it was indeed uninitialized.

**Comment by chrishoage** [comment]
Technically yes it's possible. I just find it a little odd that a user would have to specify `-1` if they wanted to have a border radius of 0. 

If you don't want to manage that bool, could the default value of the radius inside `kwm` be the same `width + 4` calculation that the overlay does? Then use what ever value the user specifies if it is set?

**Comment by koekeishiya** [comment]
Yeah I did something similar to that, worked out just fine.

**Pull request merged**
