### PR TITLE
Mouse resize

### PR DESCRIPTION
**Pull request by akdor1154**
This implements resize-with-mouse. Currently it uses the same modifier key as mouse-drag, but with the right mouse button instead of left.

Live-resize is not fast enough to have a good user experience, so instead I've used temporary borders to indicate resizing. I'd love to hook in to Apple's secret fast-resize code, but I'm not sure if it's even possible (certainly not through the accessibility API.. :( ), so borders it is for now.

Depends on the overlaylib PR, as otherwise I'm not able to remove the temporary borders!

### CODE REVIEW

**Comment by dominiklohmann** [comment]
This is amazing.  👍

**Comment by koekeishiya** [comment]
Works great.

I'll be fixing some curly brace placement and indentations after merging.

Thanks!

**Comment by akdor1154** [comment]
No worries, hope it's not too ugly! If I'd realised you'd merge straight
away I'd have flattened the commits, sorry!

**Comment by koekeishiya** [comment]
> hope it's not too ugly! If I'd realised you'd merge straight away I'd have flattened the commits, sorry!

It's all good. Thanks again : >

**Comment by cHoco** [comment]
Great work! 👍

**Pull request merged**
