### PR TITLE
Better math logic for border position and radius

### PR DESCRIPTION
**Pull request by chrishoage**
Take 2. 

Applied a 1.75 modifier to the border radius, also applied the border offset to the width and height as well as the x and y.

### CODE REVIEW

**Comment by chrishoage** [comment]
Actually, the 1.75 modifier _might_ not be needed with my other change. 

Please play with it before merging and remove it if you feel it does not help.

**Comment by koekeishiya** [comment]
hmm it still seems a bit off for me. Doesn't have the same smooth feeling as it currently does.
Do we need to change how works?

**Comment by chrishoage** [comment]
I suppose not, I just figured supporting wider border widths would be nice. Right now they start to encroach inside the window for wider borders.

keep this open for now and I'll try and refine it some more.

**Comment by chrishoage** [comment]
Ok, I've played with it a lot, and this feels the best. It also solves this case: 

Before this PR:
screen shot 2016-02-07 at 4 54 50 pm

After this PR:
screen shot 2016-02-07 at 5 51 38 pm


I tested down to a width of 2 all the way to a width of 16 and this feels pretty good.

**Comment by koekeishiya** [comment]
Looks pretty good now, better than before I would say as well. Great :>

**Comment by chrishoage** [comment]
Ultimately I think that this should just be another config setting: 

`kwmc config prefix-border radius 4` 

It would allow for the radius to look exactly as desired, however I think what's here now is pretty good for the time being.

**Comment by koekeishiya** [comment]
That could be implemented very quickly from my part in Kwm at least, if you want to just get it over with right now.

Also on an unrelated note, regarding the "random" segfaults, I have not had this happen to me in the last 3days, so the debugging process is very slow. You wouldn't happen to have `gdb` installed and be able to run a debug build of Kwm in there? If the crashes appear more frequently for you that is.

**Comment by chrishoage** [comment]
I'll tackle the radius option in kwm-overlay next weekend. 

I actually haven't been having any seg faults either, but I've been keeping pretty up to date so I'm not sure exactly when they stopped. 

If they start to appear again I will do that though.

**Comment by koekeishiya** [comment]
Aight sounds good, really appreciate it.

**Comment by koekeishiya** [comment]
I went ahead and did the required changes for Kwm.

I pass the radius setting at the end (after the width), as: `rad: floating-point`
The entirety looks something like:`id r:1 g:0 b:0 a:1 s:4 rad:4`

**Comment by oetting** [comment]
Maybe stroke offset should be a setting in-sted. This would allow borders outside the Window.

It might be an idea to have kwm-overlay read its own settings to reduce the coupling between the apps. This would allow the interface between kwm and kwm-overlay to be only about border types and positions, and let kwm-overlay focus on how those borders should look.

**Pull request merged**
