### PR TITLE
Add wrapping functionality to the new north/south/east/west movement

### PR DESCRIPTION
**Pull request by oetting**
This adds wrapping functionality by "moving" windows that are on the 
right axis but in the wrong direction to the correct side of the movement. 
The windows are moved by either adding or subtracting the window height/width.

Maybe the IsWindowInDirection function should be renamed. I don't really know
if IsWindowOnAxis is a better name.

### CODE REVIEW

**Comment by koekeishiya** [comment]
As far as I can tell, this would break the configuration option `kwmc config cycle-focus`, and I can therefore not merge this as of now.

I do plan on implement changes to allow for what you've done here in the future.

**Comment by oetting** [comment]
I missed that.
I guess it should only cycle focus if the cycle-focus option is not disabled. I have added a commit that does that, and also handles moving to the next or previous screen from the first or last leaf node. 

Maybe moving to the next or previous screen has to be better, so that it is possible to move east of west into the next screen from any row.

**Comment by koekeishiya** [comment]
> Maybe moving to the next or previous screen has to be better, so that it is possible to move east of west into the next screen from any row.

That would be my preferred behaviour.
I'll let this be for now, and take a look at it in the future, thanks tho.

**Comment by oetting** [comment]
Fair enough. 

One could argue that if you use "cycle-focus screen" then the functionality in this pull-request is the correct behaviour.

**Comment by koekeishiya** [comment]
It does indeed work, I'm just thinking that refactoring some of the code may be worth doing to implement this in a more streamlined fashion.

**Comment by koekeishiya** [comment]
This has now been added, while retaining a structure that can easily change behaviour through `kwmc config cycle-focus`

**Comment by oetting** [comment]
Awesome

**Pull request closed without merging**
