### PR TITLE
add hotkey-border command

### PR DESCRIPTION
**Pull request by a-morales**
Added a command where the border for the currently focused can be changed when a hotkey has been entered and the prefix hasn't reached its timeout.

### CODE REVIEW

**Comment by a-morales** [comment]
@koekeishiya I have my vim configuration set up with
```
autocmd BufWritePre * :%s/\s\+$//e
```
Which trims trailing whitespace on save and explains all the one lines diffs removing the whitespace. I don't see an argument for having trailing whitespace on a project, but if you want to leave it in, then I can disable it for this project

**Comment by koekeishiya** [comment]
> Which trims trailing whitespace on save and explains all the one lines diffs removing the whitespace. I don't see an argument for having trailing whitespace on a project, but if you want to leave it in, then I can disable it for this project

The random trailing spaces are not on purpose indeed, I'll be putting that in my .vimrc as well. Thanks!

Regarding this PR, I'm thinking it's kinda time for actual doing borders properly ,considering there are now 3 of them. Instead of having 3x the same variables inside kwm_border, we should probably have 
kwm_border FocusedBorder, kwm_border MarkedBorder, kwm_border PrefixBorder instead.

Also I think it would be good to avoid calling the CheckPrefixTimeout on every single keydown/keyup event, as this is something I would assume could hit quite hard on performance (maybe I'm wrong tho).

**Comment by a-morales** [comment]
I do agree that having a proper border struct is probably more appropriate here, and can implement the changes. As for `CheckPrefixTimeout()` on keydown/keyup it should not be that hard on performance since it first checks if the prefix is active before doing anything, and most of the time the prefix will not be active so essentially this should just be few instructions (a couple for the function call and return, and a couple for doing the prefix check)

**Comment by koekeishiya** [comment]
I'll go ahead and merge this for now. I will probably write a proper border struct and separate them the next time I spend time on Kwm, doing the required changes.

Regarding the `CheckPrefixTimeout()`, that is true, and I hope that optimization causes this function to be inlined to avoid function overhead for something this trivial.

**Pull request merged**
