### PR TITLE
Add kwm-overlay and make command

### PR DESCRIPTION
**Pull request by chrishoage**
This adds the overlay swift code and binary to the project. I have added a `clear` command which will remove the border from the screen (useful for `marked` windows?)

I noticed some issues while using it: If you move a floating window it never updates the border. Moving focus to a screen caused the border to not appear in the correct position (when I give the overlay the windowID of the window on the other screen it positions fine, not sure what the issue is there) 

Please let me know if you have any feedback in this PR and I will address. 

Edit: Noticed more issues when applying a layout.

### CODE REVIEW

**Comment by koekeishiya** [comment]
Borders should now update after moving a floating window.
Due to technical limitations this cannot be "moved as the window is moved", but only after.

**Comment by koekeishiya** [comment]
I have no idea why it becomes misplaced on other screens.
The only thing Kwm does is pass the exact same input to stdin as I do manually.

When I pass it manually it works, when Kwm does it, it does not work?
I have checked multiple times that Kwm passes the exact same input as I did.

**Comment by chrishoage** [comment]
I have a suspicion it has to do with line 19: `let scrn: NSScreen = NSScreen.mainScreen()!`

`mainScreen` is the focused screen. When it is entered manually the focused screen wouldn't change. Do you have knowledge of the position of the windows? Can you manually pass the width, height, x, and y instead of the windowId and see if that has any effect?

**Comment by koekeishiya** [comment]
I tried passing width height x and y just now, no difference.

I did notice that changing the Y position of the screens in OSX 'screen arrangement' did seem to affect the behaviour

**Comment by koekeishiya** [comment]
Entering it manually also does not work if you do it from a terminal on that monitor.

**Comment by chrishoage** [comment]
> I tried passing width height x and y just now, no difference.

That is odd, none of the math that uses the screen dimensions is used in that code path. It _should_ work, though clearly there is something more here. 

> Entering it manually also does not work if you do it from a terminal on that monitor.

At leas there is behavior behavior. It sounds like the coordinates are different depending on what screen is focused?

**Comment by koekeishiya** [comment]
Yeah must be something like that. Not really sure what we can do about this.

**Comment by chrishoage** [comment]
I'm sure there is something to be done. I won't have time to dig deep into this for 7 hours until I am done with work, but I'll investigate what is happening. 

If you happen across any interesting information please keep me posted.

**Comment by koekeishiya** [comment]
Ok so I've managed to solve it with some simple math. At least with my setup:
Mac Display Primary: resolution 1680x1050
1 External Display (to the right): resolution: 1920x1080

**Comment by chrishoage** [comment]
I have also solved it

```
        let scrns: Array<NSScreen> = NSScreen.screens()!
        let scrn: NSScreen = scrns[0]
```

Replace Line 19 with those two lines and it appears to work?

**Comment by koekeishiya** [comment]
Indeed it does, my fix was applied to Kwm and not the Swift application itself.
I guess we should just go with the Swift fix?

**Comment by chrishoage** [comment]
Yeah, I _think_ the swift fix is the more correct one? We always want' to be calculating the position based on the origin (0, 0) which is always screen 0.

**Comment by koekeishiya** [comment]
Yeah, that's basically what I had Kwm do as I have access to the dimensions of all monitors. But having the Swift application do it seems more appropriate.

**Comment by chrishoage** [comment]
If you ever bypassed the `windowId` functionality you would probably need to apply that fix

**Comment by koekeishiya** [comment]
Does everything seem to work properly regarding the border now? If so, I'll probably do some refactoring and implement the marked border as well

**Comment by chrishoage** [comment]
Floating windows do not appear to update for me even after the move has been completed on HEAD... maybe I'm just holding it wrong?

**Comment by koekeishiya** [comment]
Uh it should trigger from "left mouse button release". There is not really a good way for Kwm to handle this tho.

**Comment by chrishoage** [comment]
Is turning it off for floating spaces and windows feasible to do in kwm? I'm kinda OK with the border just not showing up in these instances until I can investigate if it's possible to do it from swift itself.

**Comment by koekeishiya** [comment]
Assuming Kwm gives Swift the WindowID, you should be able to track it using Swift yeah.
I should be able to turn it off for floating windows and spaces.

**Comment by chrishoage** [comment]
Sounds good, it should only be a temporary solution, until I can see what it takes to do it from the overlay app. 

Excited to see the marked window border!

**Comment by chrishoage** [comment]
A quick google search tells me that I would be required to use the accessibility API in order to get window move events for windows that are not owned by the application. 

I would really like to avoid having `kwm-overlay` ask for permissions along with `kwm`, it seems excessive. Can you subscribe to a floating windows frame change notifications in `kwm` and pass the updates to `kwm-overlay`? It should be able to respond to changes pretty quickly.

**Comment by koekeishiya** [comment]
No idea how to subscribe to notifications (if even possible) in C++ code

**Comment by chrishoage** [comment]
From a quick google search it tells me that the APIs that Honer use 

https://github.com/puffnfresh/Honer.app/blob/master/Honer/HonerApplicationDelegate.m#L110

Are C(?) APIs. And those Notifications are how honer is able to keep a border overlaid on a floating window. No idea how feasible it is to use those APIs in C++ vs Obj-C though.

**Comment by koekeishiya** [comment]
I had no idea those existed. That is indeed something I can use.

**Comment by koekeishiya** [comment]
That was an amazing find, Thanks. It should be working as close to perfect as possible now.
Check the latest commit when you have time.

**Comment by chrishoage** [comment]
Seems to be working _exactly_ as well as Honer, so i'm pretty happy with the result. I'll keep an eye on performance.

**Comment by koekeishiya** [comment]
Is it possible to add a kwm-overlay command "quit" that makes the overlay terminate?

**Comment by chrishoage** [comment]
It _should_ be as simple as `exit(0)` in an `else if` block under the `clear` command. I will not have time to test that for a few hours.

**Comment by koekeishiya** [comment]
Got it working.
So the commands are as follows:

```
kwmc config focused-border enable | disable
kwmc config focused-border size int
kwmc config focused-border color aarrggbb | rrggbb

kwmc config marked-border enable | disable
kwmc config marked-border size int
kwmc config marked-border color aarrggbb | rrggbb
```

the alpha part of the color is currently not being sent to kwm-overlay (not sure if it supports this)

**Comment by chrishoage** [comment]
In theory it does (`NSColor` has support for alpha) there could be a bug in the way I am handling it though.

**Comment by koekeishiya** [comment]
Ah my bad, I forgot to make Kwm pass the alpha value..

**Comment by koekeishiya** [comment]
The makefile is unable to build the kwm-overlay for me. No idea why this happened.
(It worked just fine earlier, have not edited anything).

**Comment by chrishoage** [comment]
Does running the make file command directly give you errors in the swift file?

**Comment by koekeishiya** [comment]
If i build manually using `swiftc kwm-overlay/kwm-overlay.swift -o bin/kwm-overlay` it works fine.

**Comment by chrishoage** [comment]
Thanks! 

I have noticed that after applying a layout it does not update the border.

**Comment by koekeishiya** [comment]
Layout as in `tree restore` ?

**Comment by chrishoage** [comment]
Ah, yes. `tree restore`. Using any method of giving a window focus fixes the issue, but not until that focus command is given will it fix it.

**Comment by koekeishiya** [comment]
Fixed @latest commit

**Comment by landaire** [comment]
I had the same issue. Had to run `xcrun -sdk macosx swiftc kwm-overlay/kwm-overlay.swift -o bin/kwm-overlay` to build.

**Comment by chrishoage** [comment]
@landaire that appears to be a different issue than described above. Do you have xcode installed with the 10.11 SDK downloaded?

**Comment by landaire** [comment]
I do. Running `make` for the first time resulted in errors when building `kwm-overlay` -- errors relating to features only available on versions 10.X or above. Running `swiftc kwm-overlay/kwm-overlay.swift -o bin/kwm-overlay` couldn't find the SDK:

```
$ swiftc kwm-overlay/kwm-overlay.swift -o bin/kwm-overlay
<unknown>:0: error: cannot load underlying module for 'CoreGraphics'
<unknown>:0: note: did you forget to set an SDK using -sdk or SDKROOT?
<unknown>:0: note: use "xcrun -sdk macosx swiftc" to select the default OS X SDK installed with Xcode```

I don't do Objective-C/Swift work so maybe I didn't set something up properly in my env but the command I posted earlier makes it work fine.

**Comment by chrishoage** [comment]
The command that make runs is supposed to be 

```
swiftc -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk kwm-overlay/kwm-overlay.swift -o ./bin/kwm-overlay
```

**Pull request merged**
