### PR TITLE
Add kwmc help command

### PR DESCRIPTION
**Pull request by a-morales**
Added a help command to Kwmc that displays the usage for Kwmc/Kwm.

### CODE REVIEW

**Comment by koekeishiya** [comment]
I'm not sure if this is a change that I feel ready to make at this point in time.
Something will be done in the future, however for now I like having the commands just listed on the github page.

I'd love to do something along the lines of more specific and automated help in regards to these commands. Instead of simply getting a list of stuff, the user could do `kwmc help how to focus the next window` or something, and get more in-depth "targetted help" if that makes sense.

**Comment by a-morales** [comment]
having the automated help would be cool, but seems like it would be overkill for a project of this size. If Kwm gets large enough then it does make sense.

Also it is personal preference but running `kwmc help` in the terminal is a lot nicer than opening up the github page, especially in cases where people don't have access to the internet

**Comment by koekeishiya** [comment]
I do agree that it would be nice having access to it directly from kwmc in the terminal.
However i feel like printing all the commands is a bit too much.

What do you think about something similar to what you've currently done, but you'd add a keyword behind help to specify which cateogy to get help for.

By this I mean, say I want to know about commands to manipulate windows. I don't care about config or screen options at this point, so I'd write `kwmc help window` , and the same for screen, space, config and whatever else there is.

If you're up for doing that change I'll accept the merge. I could do the change myself as well if you don't feel like it, but think its worth having.

If no keyword is specified it could print the list of help categories or something.

**Comment by a-morales** [comment]
Hmm that seems like a reasonable compromise, I can do the changes for it

**Comment by a-morales** [comment]
@koekeishiya updated the help command. Hopefully it is better now

**Comment by koekeishiya** [comment]
Looks good, thanks.

**Pull request merged**
