### PR TITLE
Focus by application name.

### PR DESCRIPTION
**Pull request by nshi**
Focus window by application name, e.g. `kwmc window -f Emacs`

If the application is not open, ignore the command.

### CODE REVIEW

**Comment by koekeishiya** [comment]
I don't really see this as a necessary change. The query window-list function can be used with Alfred and similar applications to get window-switching behaviour (based on application or window title).

**Comment by nshi** [comment]
Query window list only returns windows in the current space. With this patch, I can switch to a window regardless of the space it's in.

**Comment by nshi** [comment]
This patch mimics the behavior of the i3 [`focus` command with criteria](https://i3wm.org/docs/userguide.html#_jumping_to_specific_windows).

**Comment by crisidev** [comment]
+1

**Comment by koekeishiya** [comment]
Merging this into master.
Thanks.

**Comment by nshi** [comment]
Thanks, @koekeishiya

**Pull request merged**
